cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'bat'
brew 'eza'
brew 'docker'
brew 'imagemagick'
brew 'spaceman-diff'
brew 'spark'
# brew 'stripe/stripe-cli/stripe'
brew 'wget'
brew 'yt-dlp'
brew 'z'

##### ToDo
# jhead
# disk-inventroy
# cleen my drive

# davinci resolve -> Not possible

cask '1password'
cask '1password-cli'
# cask 'airtable'
cask 'alfred'
cask 'ao' # Microsoft To-Fo
cask 'anydesk'
# cask 'arq'
cask 'betterdisplay'
cask 'bettermouse' # https://better-mouse.com/
cask 'brave-browser'
cask 'chatall'
cask 'cheatsheet'
cask 'cleanmymac'
cask 'colorpicker-materialdesign'
cask 'cyberduck'
cask 'diffmerge'
cask 'displaylink'
cask 'docker'
cask 'domzilla-caffeine'
cask 'dropbox'
cask 'ears'
cask 'evernote'
cask 'exifrenamer'
cask 'filemon'
cask 'firefox'
# cask 'flux'
cask 'fmail'
cask 'franz'
cask 'fujitsu-scansnap-home'
cask 'github'
cask 'gpg-suite-no-mail'
# cask 'handbrake'
cask 'hiddenbar'
cask 'istat-menus'
cask 'iterm2'
cask 'logi-options+'
cask 'maczip'
cask 'microsoft-auto-update'
cask 'microsoft-excel'
cask 'microsoft-outlook'
cask 'microsoft-teams'
cask 'microsoft-word'
cask 'mqtt-explorer'
# cask 'notion-calendar'
cak 'opera'
cask 'osxfuse'
cask 'path-finder'
# cask 'plex'
cask 'postgres-unofficial'
cask 'postico'
cask 'postman'
cask 'rectangle'
cask 'sequel-ace'
cask 'signal'
cask 'sonos'
cask 'spotify'
cask 'synology-drive'
cask 'synology-note-station-client'
cask 'telegram'
cask 'tower'
# cask 'raycast'
# cask 'warp'
cask 'visual-studio-code'
cask 'vlc'
cask 'whatsapp'
cask 'wifiman'
# cask 'zed'
cask 'zoom'