#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

case "$(uname -s)" in
  Darwin) DOTFILES_OS=darwin ;;
  Linux)  DOTFILES_OS=linux ;;
  *)      DOTFILES_OS="$(uname -s | tr '[:upper:]' '[:lower:]')" ;;
esac
export DOTFILES_OS

# install.sh runs everywhere; install.<os>.sh only on the OS it names
find . \( -name install.sh -o -name "install.${DOTFILES_OS}.sh" \) \
  | while read installer ; do sh -c "${installer}" ; done
